### ISSUE TITLE
save_json.cc compilation errors

### ISSUE THREAD

**Issue by siko1056** [Andy1978/octave-rapidjson#2]
Dear Andreas,

On my openSUSE 15.1, [RapidJSON (1.1.0)](https://software.opensuse.org/package/rapidjson) and a self compiled Octave

$ mkoctfile --version
mkoctfile, version 5.1.0

I get the following error,

[octave-rapidjson.error.txt](https://github.com/Andy1978/octave-rapidjson/files/3904130/octave-rapidjson.error.txt)

when running `make`.  It looks like protected members are used within the code.  Do only I see this issue?  `load_json.cc` compiles with a minor flaw, see next report.

Best,
Kai

**Comment by Andy1978** [comment]
Hi Kai, I have to try with your specific rapidjson version. Oh, is it this? https://github.com/Tencent/rapidjson/releases/tag/v1.1.0 from 2016? I guess you have to try with a newer version.
Since it's only a header lib you can grab it and adapt the include path in Makefile (without needing to compile or install rapidjson)

-- Andy

**Comment by siko1056** [comment]
Thanks for the prompt reply.  I try again and report back.

**Comment by siko1056** [comment]
Yep using the latest dev version of RapidJSON solved the issue:

```
octave --no-gui-libs --eval "test load_json"
PASSES 8 out of 8 tests
octave --no-gui-libs --eval "test save_json"
PASSES 21 out of 21 tests
```

Thanks for your help.

**Comment by Andy1978** [comment]
Perhaps I can ask why there wasn't a release for more than 3 years. On the other hand I consider wget/git subrepo in the build process to pull a specific/tested rapidjson cset

**Comment by siko1056** [comment]
Have you an idea how to fulfill this dependency within Octave?  Maybe a wget to a specific git_id inside `./bootstrap`?

**Comment by Andy1978** [comment]
Hm, I think we have done this before with gnulib but yes, something like that. Btw, I'm in#octave
