### ISSUE TITLE
load_json.cc use %zu for error format string.

### ISSUE THREAD

**Issue by siko1056** [Andy1978/octave-rapidjson#3]
Just a small other one, which is thought was related to Octave, but is not.  If you use

```
error ("JSON parse error: '%s' at offset %zu",
```

https://github.com/Andy1978/octave-rapidjson/blob/3ed93df80545b87a788abe5a5a10b5a659c0cf62/load_json.cc#L286

a warning with my 64-bit build is avoided.  See

https://en.wikipedia.org/wiki/Printf_format_string#Length_field

for details.  Unfortunately, I cannot come to #octave right now.  I reviewed your project and works fine for my purpose :wink:  Thanks for your help so far.

**Comment by Andy1978** [comment]
Thank you. In the meanwhile I've removed the 4.4 branch and fixed the problem with deprecates is_type -> istype in save_json so that there is only a "master" branch

**Comment by siko1056** [comment]
Your project works like a charm now :+1:
