### ISSUE TITLE
[ Not an issue ] Guidelines to use this octave wrapper

### ISSUE THREAD

**Issue by GiovanniBalestrieri** [Andy1978/octave-rapidjson#5]
I would like to use your wrapper but I have never used the C++ API liboctave.
How to install your Octave library?

Thanks Andy for your contribution!

**Comment by Andy1978** [comment]
Hi Giovanni,
on what operating system do you want to use octave-rapidjason ans how did you install GNU Octave? As basic requirement you have to be able to compile oct files (have a C++ compiler and linker, mkoctfile, liboctave and so on). Then run make (needs git), this create two files load_json.oct and save_json.oct. Place them where you want and add the to Octave search path with "addpath" (for example within you .octavrc)

**Comment by GiovanniBalestrieri** [comment]
I am using Ubuntu and have installed Octave through the Software center.
Thanks

**Comment by Andy1978** [comment]
Was the above sufficient? Should I add an "installation" section and add the above?
